CREATE TABLE Users (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    Name NVARCHAR(50) NOT NULL,
    Email NVARCHAR(50) Unique NOT NULL,
    Password NVARCHAR(50) NOT NULL,
    ImageURL NVARCHAR(MAX),
    BirthDate DateTime,
    CreatedAt DATETIME DEFAULT GETDATE(),
    UpdatedAt DATETIME DEFAULT GETDATE(),
)
GO

CREATE TABLE UserFriend(
    UserId1 INT FOREIGN KEY REFERENCES Users(Id) ON DELETE NO ACTION NOT NULL,
    UserId2 INT FOREIGN KEY REFERENCES Users(Id) ON DELETE NO ACTION NOT NULL, 
    PRIMARY KEY(UserId1,UserId2),
    CreatedAt DATETIME DEFAULT GETDATE()
)
GO

CREATE TABLE UserRequest(
    RequestedUserId INT FOREIGN KEY REFERENCES Users(Id) ON DELETE NO ACTION NOT NULL,
    UserId INT FOREIGN KEY REFERENCES Users(Id) ON DELETE NO ACTION NOT NULL,
    PRIMARY KEY(RequestedUserId,UserId),
    CreatedAt DATETIME DEFAULT GETDATE()
)
GO

CREATE TABLE Groups(
    Id INT IDENTITY(1,1) PRIMARY KEY,
    UserId INT FOREIGN KEY REFERENCES Users(Id) NOT NULL,
    Name NVARCHAR(50) NOT NULL,
    About NVARCHAR(MAX),
    ImageURL NVARCHAR(MAX),
    CreatedAt DATETIME DEFAULT GETDATE(),
    UpdatedAt DATETIME DEFAULT GETDATE()
)
GO

CREATE TABLE UserGroup(
    PRIMARY KEY (UserId, GroupId),
    UserId INT FOREIGN KEY REFERENCES Users(Id) ON DELETE NO ACTION NOT NULL,
    GroupId INT FOREIGN KEY REFERENCES Groups(Id) ON DELETE NO ACTION NOT NULL,
    CreatedAt DATETIME DEFAULT GETDATE()
)
GO

CREATE TABLE Posts(
    Id INT IDENTITY(1,1) PRIMARY KEY,
    UserId INT FOREIGN KEY REFERENCES Users(Id) ON DELETE NO ACTION NOT NULL,
    GroupId Int FOREIGN KEY REFERENCES Groups(Id),
    ImageURL NVARCHAR(MAX),
    Content NVARCHAR(MAX) NOT NULL,
    CreatedAt DATETIME DEFAULT GETDATE(),
    UpdatedAt DATETIME DEFAULT GETDATE(),
)
GO
